
trigger:
- develop
- feature/*
- main
- bugfix/*

variables:
- name: mavenoptions
  ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    value: '-DskipTests=false'
  ${{ else }}:
    value: '-DskipTests=true'
    

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: $(mavenoptions)
