# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
    - name: Install Maven 3.9.6
      run: |
        wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        tar -xvf apache-maven-3.9.6-bin.tar.gz
        sudo mv apache-maven-3.9.6 /usr/local/apache-maven
        rm apache-maven-3.9.6-bin.tar.gz
        sudo update-alternatives --install /usr/bin/mvn mvn /usr/local/apache-maven/bin/mvn 1

    - name: Check tool versions
      run: |
        java -version
        javac -version
        mvn -version

    - name: Build all packages with Maven
      run: |
        cd common-utils
        mvn -B package --file pom.xml
        cd ..
        cd LicenseDetector
        mvn -B package --file pom.xml
        cd ..
        cd plugin.npm
        mvn -B package --file pom.xml
        cd ..
        cd plugin.maven
        mvn -B package --file pom.xml
        cd ..
        cd phsyberdome-dependency-scanner
        mvn -B package --file pom.xml

